print(f"Tổng của hai số là: {m + n}")
print(f"Hiệu của hai số là: {m - n}")
print(f"Nhân hai số: {m * n}")
print(f"Chia hai số: {m / n}")
print(f"Luỹ thừa hai số{m ** n}")
print(f"Chia lấy phần nguyên hai số {m // n}")
print(f"Chia có dư của hai số{m % n}")